app = 'pawacloud-api'
primary_region = 'jnb'

[build]
  dockerfile = "backend/Dockerfile"

[env]
  ALLOWED_ORIGINS = '["https://pawacloud-web.fly.dev","http://localhost:3000"]'
  FRONTEND_URL = "https://pawacloud-web.fly.dev"
  OAUTH_REDIRECT_URI = "https://pawacloud-api-904401126919.africa-south1.run.app/auth/callback"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
